-- Condições de pagamento reutilizáveis (prazos em dias após a data de chegada / entrega).
-- Execute no SQL Editor do Supabase (uma vez), ou via CLI de migrações.

CREATE TABLE IF NOT EXISTS condicoes_pagamento (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  qtd_parcelas integer NOT NULL CHECK (qtd_parcelas >= 1 AND qtd_parcelas <= 60),
  prazos_dias jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE condicoes_pagamento IS
  'Prazos em dias corridos após a data de chegada do pedido; cada posição do array = uma parcela.';

CREATE INDEX IF NOT EXISTS idx_condicoes_pagamento_nome ON condicoes_pagamento (nome);

-- Seeds iniciais (só se a tabela estiver vazia — evita duplicar ao reexecutar)
INSERT INTO condicoes_pagamento (nome, qtd_parcelas, prazos_dias)
SELECT nome, qtd_parcelas, d
FROM (VALUES
  ('3x — 30 / 60 / 90 (padrão mercado)', 3, '[30, 60, 90]'::jsonb),
  ('2x — 75 / 105 (após entrega)', 2, '[75, 105]'::jsonb),
  ('2x — 30 / 60 (após entrega)', 2, '[30, 60]'::jsonb),
  ('1x — 28 dias (após entrega)', 1, '[28]'::jsonb)
) AS t(nome, qtd_parcelas, d)
WHERE NOT EXISTS (SELECT 1 FROM condicoes_pagamento LIMIT 1);
